// Character
export const FETCH_CHARACTER_REQUEST = 'FETCH_CHARACTER_REQUEST';
export const FETCH_CHARACTER_SUCCESS = 'FETCH_CHARACTER_SUCCESS';
export const FETCH_CHARACTER_FAILURE = 'FETCH_CHARACTER_FAILURE';
export const SET_CHARACTER = 'SET_CHARACTER';

// Columns
export const SET_COLUMNS = 'SET_COLUMNS';

// Filters
export const APPLY_COMMAND_FILTER = 'APPLY_COMMAND_FILTER';
export const APPLY_FILTERS = 'APPLY_FILTERS';

// Settings
export const APPLY_SETTINGS = 'APPLY_SETTINGS';